apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://${SHARED_CLICKHOUSE_HOST}:${SHARED_CLICKHOUSE_PORT}
    isDefault: true
    jsonData:
      defaultDatabase: ${SHARED_CLICKHOUSE_DATABASE}
      host: ${SHARED_CLICKHOUSE_HOST}
      port: ${SHARED_CLICKHOUSE_PORT}
      protocol: http
      secure: false
      server: ${SHARED_CLICKHOUSE_HOST}
      username: default
    secureJsonData:
      password: ""
