apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://3.234.211.100:8123
    isDefault: true
    jsonData:
      defaultDatabase: is459_streaming_kj
      host: 3.234.211.100
      port: 8123
      protocol: http
      secure: false
      server: 3.234.211.100
      username: default
    secureJsonData:
      password: ""
