spark.app.name                        crypto-big-data-dev
spark.master                          spark://spark-master:7077
spark.sql.session.timeZone            UTC
spark.sql.shuffle.partitions          4
spark.driver.memory                   1g
spark.executor.memory                 2g
spark.executor.cores                  2
spark.ui.showConsoleProgress          true
